### ISSUE TITLE
cluster up but unreachable

### ISSUE THREAD

**Issue by qrkourier** [inercia/k3x#34]
```bash
flatpak run --user com.github.inercia.k3x
```
```console
2023-10-29 21:58:49,712 [MainThread  ] [INFO ]  [K3D] Activating cluster 'k3s-cluster-692'
2023-10-29 21:58:49,712 [MainThread  ] [DEBUG]  [KUBECTL] Running kubectl command ('config', 'use-context', 'k3s-cluster-692')
2023-10-29 21:58:49,748 [MainThread  ] [DEBUG]  k3s-cluster-692 is the new active cluster.
```
```bash
kubectl config view -o jsonpath='{.contexts}' -o yaml
```
```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://localhost:7296
  name: k3s-cluster-692
contexts:
- context:
    cluster: k3s-cluster-692
    user: k3s-cluster-692
  name: k3s-cluster-692
current-context: k3s-cluster-692
kind: Config
preferences: {}
users:
- name: k3s-cluster-692
  user:
    password: REDACTED
    username: admin
```
```bash
curl -k https://localhost:7296/healthz
```
```console
curl: (7) Failed to connect to localhost port 7296 after 0 ms: Connection refused
```

I installed the Flatpak by clicking the install button in the Elemental AppCenter.

```bash
cat /etc/lsb-release /etc/os-release
```
```bash
DISTRIB_ID=Pop
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Pop!_OS 22.04 LTS"
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
```
